server:
  port: 8080
spring:
  application:
    name: mybatis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
mybatis:
  type-aliases-package: org.wjfiyhl.entity
  mapper-locations: classpath:org/wjfiyhl/mapper/*Mapper.xml